name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta diariamente a medianoche UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: mmontanes